---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - name: I want to execute linux command
    command: hostname -f
    register: myfiesttaskresult
  
  - name: I want to display 1st task result
    debug: 
     msg: "{{myfiesttaskresult}}"

  - name: install git
    apt:
      name: git
      state: present
    when: myfiesttaskresult.stderr !=""

  - name: install git
    apt:
      name: tree
      state: present
    when: myfiesttaskresult.stderr =""  
   