---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install web server
    apt:
      name: apache2
      state: present
  - name: copy test file into node side
    copy:
      src: mytestfile
      dest: /home/user01/
  
  - name: download remote internet file to node side
    get_url: 
     url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
     dest: /home/user01/apache-tomcat-10.0.20.tar.gz
     force_basic_auth: yes

  - name: copy index html file into node side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
