---
- hosts: webserver
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install ubuntu webserver on all the nodes
    apt:
     name: apache2
     state: present
     when: ansbile_os_family== "Debian"


  - name: i want to start ubuntu webserver on all the nodes
    service:
      name: apache2
      state: started
      when: ansbile_os_family== "Debian"
