---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: I want to install ubuntu webserver on all the nodes
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

