---
- name: grant tomcat onwership on tomcat folder
  command: sudo chown -R tomcat:tomcat /opt/tomcat/


- name: grant exeucte permission on bin folder
  command: sudo chmod -R u+x /opt/tomcat/bin
  